version: "3.9"

services:

  django-library-system:
    build:
      context: ./DJANGO-Library-System
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/DJANGO-Library-System
    ports:
      - "8010:8010"
    #command: bash -c "while true; do sleep 1000; done"

  react-library-system:
    build:
      context: ./REACT-Library-System
      dockerfile: Dockerfile
    volumes:
      - ./REACT-Library-System:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "3010:3010"
    #command: bash -c "while true; do sleep 1000; done"

volumes:
  node_modules: