# Generated by Django 4.0.6 on 2022-08-10 01:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_owner_invoice_user_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9f1c92d8-eaf9-46c0-824c-929d4c84fb37')),
        ),
    ]
