# Generated by Django 4.0.6 on 2022-08-10 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('73ec8560-cdee-4d56-b6ff-2e5b84c13013')),
        ),
    ]
