# Generated by Django 4.0.6 on 2022-08-11 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6311204-96af-446a-b80e-a498584829c4')),
        ),
    ]
