# Generated by Django 4.0.6 on 2022-08-10 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelf', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('author', models.CharField(max_length=128, verbose_name='author')),
                ('image', models.URLField(default='https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/28c76cfe-f964-49b5-9a96-41825da0dd29/d45ldtj-22284684-8c3d-464e-b6d6-94d8813819ec.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI4Yzc2Y2ZlLWY5NjQtNDliNS05YTk2LTQxODI1ZGEwZGQyOVwvZDQ1bGR0ai0yMjI4NDY4NC04YzNkLTQ2NGUtYjZkNi05NGQ4ODEzODE5ZWMucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.o-gIibMentMJilhCThKzA5sVPfEY16x_FVAQI70b2qw', max_length=1000)),
                ('year', models.IntegerField(verbose_name='publication year')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this book should be treated as active.Unselect this instead of deleting books.', verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelf.shelf')),
            ],
        ),
    ]
