# Generated by Django 4.0.6 on 2022-08-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
    ]
