# Generated by Django 4.0.6 on 2022-08-11 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('baeadf60-cd36-4a40-9908-d709db5d60a8')),
        ),
    ]
