# Generated by Django 4.0.6 on 2022-08-11 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('33b5c28d-ff6c-487f-b762-41e9354cb3e9')),
        ),
    ]
