# Generated by Django 4.0.6 on 2022-08-11 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f05f4f3a-363b-41e4-9816-5f69e31cea0c')),
        ),
    ]
