# Generated by Django 4.0.6 on 2022-08-11 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('46dc19a5-07de-4d40-a0f6-990eb9e30d60')),
        ),
    ]
