# Generated by Django 4.0.6 on 2022-08-11 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_alter_invoice_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9682e264-2e2c-4454-b695-1c9d1bb9dcd1')),
        ),
    ]
