# Generated by Django 4.0.6 on 2022-08-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_initial'),
        ('book', '0001_initial'),
        ('book_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookItem',
            new_name='Item',
        ),
    ]
