# Generated by Django 4.0.6 on 2022-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(error_messages={'unique': 'A shelf with that location already exists.'}, max_length=3, unique=True, verbose_name='shelf location')),
            ],
        ),
    ]
