# Generated by Django 4.0.6 on 2022-08-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A category with that name already exists.'}, max_length=128, unique=True, verbose_name='category name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this category should be treated as active.Unselect this instead of deleting categories.', verbose_name='active')),
            ],
        ),
    ]
